version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0
  buildevents: honeycombio/buildevents@0.2.7

# enable a job when tag created (tag create is ignored by default)
# runs for all branches and all tags
filters_always: &filters_always
  filters:
    tags:
      only: /.*/

# restrict a job to only run when a version tag (vNNNN) is created
# does not run for any branch update
filters_publish: &filters_publish
  filters:
    tags:
      only: /^v[0-9].*/
    branches:
      ignore: /.*/

executors:
  go:
    docker:
      - image: cimg/go:1.18

commands:
  build:
    steps:
      - buildevents/berun:
          bename: build
          becommand: make
  # lint: # this uses golangci-lint which isn't compatible with go1.18
  #   steps:
  #     - buildevents/berun:
  #         bename: lint
  #         becommand: make lint
  build_packages:
    steps:
      - buildevents/berun:
          bename: build_packages
          becommand: make package
  draft_github_release:
    steps:
      - buildevents/berun:
          bename: draft_github_release
          becommand: make publish_github
  sync_s3_artifacts:
    steps:
      - buildevents/berun:
          bename: sync_s3_artifacts
          becommand: make publish_s3
  save_go_cache:
    steps:
      - save_cache:
          key: cache1-go-mod-{{ checksum "go.sum" }}
          paths:
            - go/pkg/mod
  restore_go_cache:
    steps:
      - restore_cache:
          key: cache1-go-mod-{{ checksum "go.sum" }}
  install_ghr:
    steps:
      - run:
          name: Install ghr for drafting GitHub Releases
          command: go install github.com/tcnksm/ghr@latest

jobs:
  setup:
    executor: go
    steps:
      - buildevents/start_trace
  watch:
    executor: go
    steps:
      - buildevents/watch_build_and_finish
  build:
    executor: go
    steps:
      - buildevents/with_job_span:
          steps:
            - buildevents/start_trace
            - checkout
            - build
            # - lint
            # - test
            - save_go_cache
            - persist_to_workspace:
                root: .
                paths: [ . ]
  release:
    executor: go
    steps:
      - buildevents/with_job_span:
          steps:
            - install_ghr
            - aws-cli/install
            - aws-cli/setup
            - attach_workspace:
                at: .
            - build_packages
            - draft_github_release
            - sync_s3_artifacts

workflows:
  version: 2
  ci:
    jobs:
      - setup:
          <<: *filters_always
      - watch:
          <<: *filters_always
          context: Honeycomb Secrets for Public Repos
          requires:
            - setup
      - build:
          <<: *filters_always
          requires:
            - setup
      - release:
          <<: *filters_publish
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
