version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

# enable a job when tag created (tag create is ignored by default)
# runs for all branches and all tags
filters_always: &filters_always
  filters:
    tags:
      only: /.*/

# do not run jobs on external PRs and dependabot
filters_internal: &filters_internal
  filters:
    tags:
      only: /.*/
    branches:
      ignore:
        - /pull\/.*/
        - /dependabot\/.*/

# restrict a job to only run when a version tag (vNNNN) is created
# does not run for any branch update
filters_publish: &filters_publish
  filters:
    tags:
      only: /^v[0-9].*/
    branches:
      ignore: /.*/

executors:
  go:
    docker:
      - image: cimg/go:1.18

commands:
  build:
    steps:
      - run:
          name: build
          command: make
  # lint: # this uses golangci-lint which isn't compatible with go1.18
  #   steps:
  #     - run:
  #         name: lint
  #         command: make lint
  build_packages:
    steps:
      - run:
          name: build_packages
          command: make package
  draft_github_release:
    steps:
      - run:
          name: draft_github_release
          command: make publish_github
  sync_s3_artifacts:
    steps:
      - run:
          name: sync_s3_artifacts
          command: make publish_s3
  save_go_cache:
    steps:
      - save_cache:
          key: cache1-go-mod-{{ checksum "go.sum" }}
          paths:
            - go/pkg/mod
  restore_go_cache:
    steps:
      - restore_cache:
          key: cache1-go-mod-{{ checksum "go.sum" }}
  install_ghr:
    steps:
      - run:
          name: Install ghr for drafting GitHub Releases
          command: go install github.com/tcnksm/ghr@latest

jobs:
  build:
    executor: go
    steps:
      - checkout
      - build
      # - lint
      # - test
      - save_go_cache
      - persist_to_workspace:
          root: .
          paths: [ . ]
  release:
    executor: go
    steps:
      - install_ghr
      - aws-cli/install
      - aws-cli/setup
      - attach_workspace:
          at: .
      - build_packages
      - draft_github_release
      - sync_s3_artifacts

workflows:
  version: 2
  ci:
    jobs:
      - build:
          <<: *filters_always

      - release:
          <<: *filters_publish
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
