version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.22
  buildevents: honeycombio/buildevents@0.2.7

# enable a job when tag created (tag create is ignored by default)
# runs for all branches and all tags
filters_always: &filters_always
  filters:
    tags:
      only: /.*/

# restrict a job to only run when a version tag (vNNNN) is created
# does not run for any branch update
filters_publish: &filters_publish
  filters:
    tags:
      only: /^v[0-9].*/
    branches:
      ignore: /.*/

executors:
  go:
    docker:
      - image: cimg/go:1.15.8

commands:
  save_go_cache:
    steps:
      - save_cache:
          key: cache1-go-mod-{{ checksum "go.sum" }}
          paths:
            - go/pkg/mod

  restore_go_cache:
    steps:
      - restore_cache:
          key: cache1-go-mod-{{ checksum "go.sum" }}

jobs:
  setup:
    executor: go
    steps:
      - buildevents/start_trace
  watch:
    executor: go
    steps:
      - buildevents/watch_build_and_finish
  build:
    executor: go
    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID build -- make
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID lint -- make lint
          # - run: buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID test -- make test
            - save_go_cache
            - persist_to_workspace:
                root: .
                paths: [ . ]

  release:
    executor: go
    steps:
      - buildevents/with_job_span:
          steps:
            - attach_workspace:
                at: .
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID native-deps -- sudo apt update && sudo apt install python-is-python3 python3-pip
            - aws-cli/setup:
                aws-access-key-id: AWS_ACCESS_KEY_ID
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY
                aws-region: AWS_REGION
            - restore_go_cache
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID package -- make package
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $BUILDEVENTS_SPAN_ID release -- make release

workflows:
  version: 2
  ci:
    jobs:
      - setup:
          <<: *filters_always
      - watch:
          <<: *filters_always
          context: Honeycomb Secrets for Public Repos
          requires:
            - setup
      - build:
          <<: *filters_always
          requires:
            - setup
      - release:
          <<: *filters_publish
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
